---
apiVersion: v1
clusters:
- cluster:
    server: https://host.docker.internal:6443
    insecure-skip-tls-verify: true
  name: k3d-kubecon-NA25
contexts:
- context:
    cluster: k3d-kubecon-NA25
    user: admin@k3d-kubecon-NA25
  name: k3d-kubecon-NA25
current-context: k3d-kubecon-NA25
kind: Config
preferences: {}
users:
- name: admin@k3d-kubecon-NA25
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrRENDQVRlZ0F3SUJBZ0lJYmZJR3dTbVhCOW93Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOell5TlRVNU1EQTVNQjRYRFRJMU1URXdOekl6TkRNeU9Wb1hEVEkyTVRFdwpOekl6TkRNeU9Wb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJMSEg5aUt5eExISlBPZU0KNjREbzNEai9Ra0pieFRQclZSaWEvVTZrc0N0b2gwL09FOW8vTXpMSzMwam4wS2hYTDhDaHNPL09CYW9JVmhxbApNQzJodXhTalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCVE9udkZrL2ZNeGlmNHMwcjlRMHhnUktlN1NkakFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlBTWgwRERMTUNvNStqN1ZVVXZZUFdMb29iZ0F5aElaR0FLc2tCS0dtM014d0lnWnFsaTVWMU5KSGNwV3RnMAozUnVCbEdDNU4ra013dmRrS050ektWdG15SEU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTmpJMU5Ua3dNRGt3SGhjTk1qVXhNVEEzTWpNME16STVXaGNOTXpVeE1UQTFNak0wTXpJNQpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTmpJMU5Ua3dNRGt3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSUExCK0FiK2xoNVF4RGlZbk9rQ0IvWU84QTdBMlFKSUZMWTB5UDJkcnMKVVB4bUYzWCsySUduREVhSVNXV3hFTEFQRlZLY0czNngvVTJkUmNvNCtQTnNvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXpwN3haUDN6TVluK0xOSy9VTk1ZCkVTbnUwbll3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnVjhBTXhNV2xEckNXd1p5UGE2YWJxaXhsd3VBN2RJVEEKcytoeDBCUk8vUlFDSUFJZUdUQVpnSWJYdGliRTVZcWZlQlVLVllnMzBWZE9hd1ZlT0J4aVdsTXIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUhyd3RaZExYUlg5dkNlQkw2VnA0U1AyTTk5OE16SmdTZE03ODYzZHc2RjdvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFc2NmMklyTEVzY2s4NTR6cmdPamNPUDlDUWx2Rk0rdFZHSnI5VHFTd0syaUhUODRUMmo4egpNc3JmU09mUXFGY3Z3S0d3Nzg0RnFnaFdHcVV3TGFHN0ZBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
