apiVersion: v1
kind: ConfigMap
metadata:
  name: product-api-config
  labels:
    app: imp-product-catalog
    component: backend
data:
  AWS_REGION: "us-west-2"
  S3_BUCKET_NAME: "tenant-atlantis-product-images-imperative"
  PORT: "8080"
  LOG_LEVEL: "INFO"
