apiVersion: v1
kind: Service
metadata:
  name: imp-product-catalog
  labels:
    app: imp-product-catalog
    component: backend
spec:
  type: ClusterIP
  selector:
    app: imp-product-catalog
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: None
